app = "sport24wire-restream"

[env]
  HLS_URL = "https://cu.ebda3io.store/nppsf3.m3u8"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
